name: Create PDF release from markdown

on:
  push:
    branches:
      - main
      - md-frontmatter-support
  workflow_dispatch:

jobs:
  convert_via_pandoc_and_release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir .old &&
          rsync -vr ./* .old/ --exclude .old &&
          awk '/!\[/{gsub(/<!--/,"{");gsub(/-->/,"}")};{gsub("<!--pagebreak-->","\\pagebreak")};{gsub("<!--newpage-->","\\newpage")};{gsub("<!--clearpage-->","\\clearpage")};{gsub("<!----------","---")};{gsub("---------->","...")};{print}' .old/DBS/README.md > DBS/README.md &&
          awk '/!\[/{gsub(/<!--/,"{");gsub(/-->/,"}")};{gsub("<!--pagebreak-->","\\pagebreak")};{gsub("<!--newpage-->","\\newpage")};{gsub("<!--clearpage-->","\\clearpage")};{gsub("<!----------","---")};{gsub("---------->","...")};{print}' .old/SWE/README.md > SWE/README.md &&
          awk '/!\[/{gsub(/<!--/,"{");gsub(/-->/,"}")};{gsub("<!--pagebreak-->","\\pagebreak")};{gsub("<!--newpage-->","\\newpage")};{gsub("<!--clearpage-->","\\clearpage")};{gsub("<!----------","---")};{gsub("---------->","...")};{print}' .old/PRO/README.md > PRO/README.md &&
          awk '/!\[/{gsub(/<!--/,"{");gsub(/-->/,"}")};{gsub("<!--pagebreak-->","\\pagebreak")};{gsub("<!--newpage-->","\\newpage")};{gsub("<!--clearpage-->","\\clearpage")};{gsub("<!----------","---")};{gsub("---------->","...")};{print}' .old/RES/README.md > RES/README.md &&
          awk '/!\[/{gsub(/<!--/,"{");gsub(/-->/,"}")};{gsub("<!--pagebreak-->","\\pagebreak")};{gsub("<!--newpage-->","\\newpage")};{gsub("<!--clearpage-->","\\clearpage")};{gsub("<!----------","---")};{gsub("---------->","...")};{print}' .old/NET/README.md > NET/README.md
      - run: |
          mkdir output
      - uses: docker://rstropek/pandoc-latex:latest # generate DBS pdf
        with:
          args: --output=output/DBS.pdf --resource-path=DBS/ --template https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/v1.4.0/eisvogel.tex --pdf-engine=xelatex --listings -f markdown+raw_tex --verbose DBS/README.md
      - uses: docker://rstropek/pandoc-latex:latest # generate SWE pdf
        with:
          args: --output=output/SWE.pdf --resource-path=SWE/ --template https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/v1.4.0/eisvogel.tex --pdf-engine=xelatex --listings -f markdown+raw_tex --verbose SWE/README.md
      - uses: docker://rstropek/pandoc-latex:latest # generate PRO pdf
        with:
          args: --output=output/PRO.pdf --resource-path=PRO/ --template https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/v1.4.0/eisvogel.tex --pdf-engine=xelatex --listings -f markdown+raw_tex --verbose PRO/README.md
      - uses: docker://rstropek/pandoc-latex:latest # generate RES pdf
        with:
          args: --output=output/RES.pdf --resource-path=RES/ --template https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/v1.4.0/eisvogel.tex --pdf-engine=xelatex --listings -f markdown+raw_tex --verbose RES/README.md
      - uses: docker://rstropek/pandoc-latex:latest # generate NET pdf
        with:
          args: --output=output/NET.pdf --resource-path=NET/ --template https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/v1.4.0/eisvogel.tex --pdf-engine=xelatex --listings -f markdown+raw_tex --verbose NET/README.md
      - uses: actions/upload-artifact@master # upload pdfs as an artifact
        with:
          name: output
          path: output
      - uses: meeDamian/github-release@2.0 # create/override a release and attach a pdf
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          tag: pdf-release
          name: PDFs
          body: Automated release
          gzip: false
          files: output/DBS.pdf
          allow_override: true
      - uses: meeDamian/github-release@2.0 # override release to attach another pdf
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          tag: pdf-release
          name: PDFs
          body: Automated release
          gzip: false
          files: output/PRO.pdf
          allow_override: true
      - uses: meeDamian/github-release@2.0 # override release to attach another pdf
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          tag: pdf-release
          name: PDFs
          body: Automated release
          gzip: false
          files: output/SWE.pdf
          allow_override: true
      - uses: meeDamian/github-release@2.0 # override release to attach another pdf
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          tag: pdf-release
          name: PDFs
          body: Automated release
          gzip: false
          files: output/NET.pdf
          allow_override: true
      - uses: meeDamian/github-release@2.0 # override release to attach another pdf
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          tag: pdf-release
          name: PDFs
          body: Automated release
          gzip: false
          files: output/NET.pdf
          allow_override: true
